apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iitd-staging

resources:
  - ../../base

namePrefix: staging-

replicas:
  - name: iitd-server
    count: 1

images:
  - name: ghcr.io/your-org/iitd/server
    newTag: develop

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment

commonLabels:
  environment: staging

