apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
  namespace: default
data:
  jwt-expires-in: "1d"
  smtp-host: "smtp.gmail.com"
  smtp-port: "587"
  smtp-from: "IITD System <noreply@iitd.ac.in>"

