apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iitd

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml

commonLabels:
  app: iitd-server
  managed-by: kustomize

images:
  - name: ghcr.io/your-org/iitd/server
    newTag: latest

