apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
  labels:
    app: server
data:
  NODE_ENV: "production"
  PORT: "3000"
  MONGODB_URI: "mongodb://mongodb:27017/iitd-db"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_SECURE: "false"

