apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iitd

resources:
  - namespace.yaml
  - mongodb.yaml
  - server.yaml
  - client.yaml
  - configmap.yaml
  - secrets.yaml
  - ingress.yaml

commonLabels:
  app: iitd
  managed: gitops

