apiVersion: v1
kind: ServiceAccount
metadata:
  name: iitd-sa
  namespace: iitd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: iitd-role
  namespace: iitd
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets", "pods", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: iitd-rolebinding
  namespace: iitd
subjects:
- kind: ServiceAccount
  name: iitd-sa
  namespace: iitd
roleRef:
  kind: Role
  name: iitd-role
  apiGroup: rbac.authorization.k8s.io

